language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# install: sudo apt-get -qq install python3-numpy python3-scipy
install:
  - pip install -r requirements.txt
script:
  - python setup.py clean
  - python setup.py build_ext --inplace
  - python setup.py install
deploy:
  provider: pypi
  user: Rodney.Persky
  password:
    secure: Uxa1n3eKoNSy67q1o0ZCr4WQPj4BbUvcNDY+TqinWstQNySEN+WtcFkPCHEEGW7klviAxB/vVIeoiNewSa7PYDIo1By1VLR2XsJPgznTiruXyLNu4XOFDMfDpQCmkrZ4GnjghDqmXwqzUQUwopMPD5mMCHc+M1gUvuY4zWst4hI=
  on:
    repo: Rod-Persky/pyIGES
